### ISSUE TITLE
Can't import bundled version in nodejs

### ISSUE THREAD

**Issue by davidyuk** [antelle/argon2-browser#64]
```
$ node
Welcome to Node.js v14.16.0.
Type ".help" for more information.
> require('argon2-browser/dist/argon2-bundled.min')
Uncaught ReferenceError: self is not defined
    at Object.<anonymous> (/.../node_modules/argon2-browser/dist/argon2-bundled.min.js:4:2)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
```

argon2-browser version is 1.17.0

At the same time, `argon2-browser/lib/argon2.js` works fine, but we would prefer to don't import wasm files because our lib has multiple ways to use and this would complicate installation for end users.

**Comment by antelle** [comment]
Thanks! Fixed in v1.18.0
